apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetslab
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetslab
  template:
    metadata:
      labels:
        app: kubernetslab
    spec:
      containers:
      - name: kubernetslab
        image: icaroferreira/kubernetslab:latest
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name:  kubernetslab
spec:
  selector:
    app:  kubernetslab
  ports:
  - port:  80
    targetPort:  8080
    nodePort: 30000
  type:  NodePort   
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123123"
        - name: MYSQL_DATABASE
          value: "exampledb"
        - name: MYSQL_USER
          value: "testeuser"
        - name: MYSQL_PASSWORD
          value: "123123"
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql
  type: ClusterIP