apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetslab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetslab
  template:
    metadata:
      labels:
        app: kubernetslab
    spec:
      containers:
      - name: kubernetslab
        image: icaroferreira/kubernetslab:latest
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name:  kubernetslab
spec:
  selector:
    app:  kubernetslab
  ports:
  - port:  80
    targetPort:  8080
    nodePort: 30000
  type:  NodePort    
          